// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { RoomId } from "./RoomId";

export type Presentation = { current_slide: number, slide_data: Array<JsonValue>, clients: Array<string>, created_at: string, id: RoomId, };
