// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomId } from "./RoomId";

export type RoomCommand = { "type": "JoinRoom", room_id: RoomId, } | { "type": "LeaveRoom", room_id: RoomId, };
