// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoomEvent = { "type": "RoomJoined", user_id: string, } | { "type": "RoomLeft", user_id: string, };
