// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClientMessage<T> = { payload: T, client_id: string | null, request_id: string | null, };
