// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomId } from "./RoomId";

export type CommandMessage<T> = { payload: T, room_id: RoomId, };
