// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type CreateRoomRequest = { organisation_id: string, room_type: string, name: string, slide_data: Array<JsonValue> | null, };
