// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomId } from "./RoomId";

export type ServerMessage<T> = { room_id: RoomId, payload: T, datetime: string, sender_id: string | null, request_id: string | null, broadcast: boolean | null, };
