// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JoinRoomEvent } from "./JoinRoomEvent";
import type { JoinRoomPayload } from "./JoinRoomPayload";
import type { LeaveRoomEvent } from "./LeaveRoomEvent";
import type { LeaveRoomPayload } from "./LeaveRoomPayload";
import type { Message } from "./Message";

export type Event = Message<JoinRoomEvent, JoinRoomPayload> | Message<LeaveRoomEvent, LeaveRoomPayload>;

