// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Message<E, T> = { type: E, payload: T, id: number | null, in_reply_to: number | null, };
