// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomId } from "./RoomId";

export type PresentationCommand = { "type": "JoinPresentation", client_id: string, socket_id: string, room_id: RoomId, } | { "type": "LeavePresentation", room_id: RoomId, client_id: string, } | { "type": "ChangeSlide", room_id: RoomId, slide_index: number, };
