// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Presentation } from "./Presentation";

export type Room = { "type": "Presentation", "payload": Presentation };
