// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerMessage<T> = { payload: T, datetime: string, sender_id: string | null, request_id: string | null, broadcast: boolean | null, };
