// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Room } from "./Room";
import type { RoomId } from "./RoomId";

export type GetRoomsResponse = { rooms: Array<[RoomId, Room]>, };
