// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PresentationEvent = { "type": "PresentationJoined", client_id: string, } | { "type": "PresentationLeft", client_id: string, } | { "type": "SlideChanged", slide_index: number, };
