// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomId } from "./RoomId";

export type PresentationEvent = { "type": "PresentationJoined", socket_id: string, room_id: RoomId, } | { "type": "PresentationLeft", socket_id: string, room_id: RoomId, } | { "type": "SlideChanged", slide_index: number, };
